### ISSUE TITLE
V17.10 linux compiling zcashd Internal compiler error

### ISSUE THREAD

**Issue by Alternating** [HarrKxx/eleos#11]
Internal compiler error Segementation fault

Crypto/x509/x509_vfw.c:3275:1 Internal compiler error: Segmentation fault

makefile:3770 recipe for target `Crypto/x509/x509_vfy.o` failed

**Comment by HarrKxx** [comment]
You can take zclassic already compile here : https://github.com/HarrKxx/eleos/releases
