### ISSUE TITLE
Wallet Daemon Cannot be run

### ISSUE THREAD

**Issue by savagecorp** [HarrKxx/eleos#12]
<img width="620" alt="screen shot 2018-01-04 at 12 52 41 pm" src="https://user-images.githubusercontent.com/895868/34577216-648f291e-f14e-11e7-9537-44e1eab5c0b3.png">

Got this on my MBP. Install was fine, but throwing this error and click okay quits the app.

**Comment by HarrKxx** [comment]
Do you have the last version ? https://github.com/HarrKxx/eleos/releases/download/0.1/zclassic1.2.1.dmg ?

**Comment by savagecorp** [comment]
![zclassic-js](https://user-images.githubusercontent.com/895868/34577503-53fda566-f14f-11e7-86f6-ae9d2ae0af21.gif)

yup.

**Comment by savagecorp** [comment]
Yes. Installs great, but while initializing I get this error.

**Comment by savagecorp** [comment]
Updated to High Sierra OS, issue resolved.
