### ISSUE TITLE
v17.10 - Failed eleos script - copy/paste in body of issue

### ISSUE THREAD

**Issue by Alternating** [HarrKxx/eleos#15]
testpc@testpc-linux:~/eleos-0.1$ npm start

> eleos@0.0.9 start /home/testpc/eleos-0.1
> electron .

/home/testpc/eleos-0.1/node_modules/electron/dist/electron: error while loading                                                             shared libraries: libgconf-2.so.4: cannot open shared object file: No such file                                                             or directory

npm ERR! Linux 4.13.0-21-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! eleos@0.0.9 start: `electron .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the eleos@0.0.9 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the eleos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs eleos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls eleos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/testpc/eleos-0.1/npm-debug.log

**Comment by HarrKxx** [comment]
Problem with library : libgconf-2.so.4
apt-get install libgconf-2-4 should do the trick.
