### ISSUE TITLE
Glitch in History Tab

### ISSUE THREAD

**Issue by Fritzerton** [HarrKxx/eleos#16]
I've noticed on certain transactions, if you click "details", then ok to close detail windows, then click details again, the list will glitch for a second and show all transactions twice. It only lasts for a second or two then goes back to normal. Not all transactions do it either.
<img width="902" alt="duplicate tx" src="https://user-images.githubusercontent.com/35083649/34613145-b00eb024-f1fa-11e7-9c45-d781c5f153b8.png">

**Comment by darthcrypto87** [comment]
I can't reproduce that with the latest installer release.

**Comment by Fritzerton** [comment]
After closing the wallet and reopening, I can't reproduce it either. It wasn't a big deal or anything that affected usability, just a small glitch I noticed.
