### ISSUE TITLE
Javascript Error when open wallet for the first time

### ISSUE THREAD

**Issue by savagecorp** [HarrKxx/eleos#2]
I downloaded the Osx testing .dmg. Installed it, and upon opening this error occurs. If I close and open the application again nothing happens. 
![screen shot 2018-01-03 at 6 49 33 pm](https://user-images.githubusercontent.com/895868/34544927-4f91f2e0-f0b7-11e7-9d8b-b3b5581777e4.png)

**Comment by HarrKxx** [comment]
Hello,

Can you test with the new version, thank you.

**Comment by savagecorp** [comment]
Version 1.2.1 still giving the same error.

**Comment by HarrKxx** [comment]
Can you verify if you have a zclassic folder with zclassic.conf in it.
Hidden folder probably in your user folder.

**Comment by savagecorp** [comment]
Nope.. It's not creating one in Application Support - Im on a iMac if that helps. (I did try this on my macbook pro, and it does create the zclassic folder and zclassic.conf file)

**Comment by HarrKxx** [comment]
Looks like a permission problem on some mac.

**Comment by savagecorp** [comment]
![zclassic-js](https://user-images.githubusercontent.com/895868/34578926-d66c1528-f154-11e7-9054-b691f9e3fef6.gif)

**Comment by HarrKxx** [comment]
CAn I have the latest from the crash report.
Thanks.

**Comment by savagecorp** [comment]
How does one do that?

**Comment by savagecorp** [comment]
I still get this error after updating to High Sierra, @HarrKxx 

![screen shot 2018-01-05 at 9 54 14 am](https://user-images.githubusercontent.com/895868/34614178-8ab41f04-f1fe-11e7-96cc-70752437865d.png)

**Comment by HarrKxx** [comment]
CAn I have the latest from the crash report.
Thanks.

**Comment by savagecorp** [comment]
How do I get that ?

**Comment by HarrKxx** [comment]
https://bjango.com/help/crashlogmac/

**Comment by savagecorp** [comment]
[zcld-mac_2017-12-30-184318.crash.zip](https://github.com/HarrKxx/eleos/files/1607305/zcld-mac_2017-12-30-184318.crash.zip) @HarrKxx crash report
