### ISSUE TITLE
Wallet daemon cannot be run.

### ISSUE THREAD

**Issue by eestevez1** [HarrKxx/eleos#7]
<img width="691" alt="screen shot 2018-01-03 at 5 53 22 pm" src="https://user-images.githubusercontent.com/9285476/34544995-6965a318-f0af-11e7-9f88-bfb1e9b6f10c.png">

<img width="514" alt="screen shot 2018-01-03 at 5 56 35 pm" src="https://user-images.githubusercontent.com/9285476/34545001-76771212-f0af-11e7-95ee-0298bcb7ea14.png">

I have tried restarting the application and same error. Going to reboot MAC and test again. Will upgrade system if no success and I'll report back.

**Comment by Fritzerton** [comment]
I'm running OS X High Sierra 10.13.2 and getting the same thing.

**Comment by mushupork** [comment]
Seeing the same issue on Mac Sierra 10.12, ZCashParams and Zclassic folders exist in Library/Application Support

**Comment by thcsmith** [comment]
Same issue on High Sierra 10.13.3 (MacOS beta)

**Comment by HarrKxx** [comment]
Hello,

We resolve this problem, please test again with the new version.

Thank you.
