### ISSUE TITLE
Error Initializing - MAC

### ISSUE THREAD

**Issue by Fritzerton** [HarrKxx/eleos#8]
After opening wallet I get an error box that says "Wallet daemon can not be run. Check if daemon does not run already."
![screen shot 2018-01-03 at 6 56 02 pm](https://user-images.githubusercontent.com/35083649/34545054-19e9713a-f0b8-11e7-970b-bc3fcb856262.png)

**Comment by Fritzerton** [comment]
I'm running OS X High Sierra 10.13.2

**Comment by HarrKxx** [comment]
Hello,

We resolve this problem, please test again with the new version.

Thank you.

**Comment by Abencheikh1984** [comment]
I have the same issue please help me
