### ISSUE TITLE
Sync status 0

### ISSUE THREAD

**Issue by rankify** [HarrKxx/eleos#9]
Even tried adding custom nodes. Maybe I need to unlock some port with my router?

**Comment by Bellatrixie** [comment]
If you added custom nodes then it should work fine i think. You can just download old zclassic.conf from here https://github.com/z-classic/zclassic/releases and copypaste it in AppData\Roaming\Zclassic
If it's not working now, then idk, maybe firewall doesn't let you connect. I have router with all ports closed and wallet is working okay for me atm.

**Comment by HarrKxx** [comment]
Thanks Bellatrixie.
